name: Vysteria-Mining
version: ${project.version}
main: dev.xcodiq.vysteriamining.Mining
authors: [xCodiq, Vysteria]
depend: [WorldGuard, Vysteria-Library]
description: Vysteria Mining | Region based mines for ores with /ores menu
website: www.vysteria.com
